export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Logout } from './Logout';
export { default as Customers } from './Customers';
export { default as Categories } from './Categories';
export { default as Coupons } from './Coupons';
export { default as Products} from './Products';
export { default as ProductCategories } from './ProductCategories';
export { default as Settings } from './Settings';
export { default as Orders} from './Orders';
export { default as ForgotPassword } from './ForgotPassword';
export { default as ResetPassword } from './ResetPassword';